---
- hosts: localhost
  vars:
    _ansible_dir: /tmp/ansible/templates
    name:
      funding_source: funding1
      project: project1
      namespace:
        - namespace1
    requests:
      pods: "2"
      cpu: "2"
      memory: "4Gi"
      storage: "100Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
    lrange:
      pod:
        max_cpu: 1
        max_memory: 1
        min_cpu: 3
        min_memory: 1
      container:
        default_cpu: 1
        default_memory: 1
        defaultRequest_cpu: 1
        defaultRequest_memory: 1

  tasks:
    - include_tasks: playbooks/quota_create.yml