---
- name: Create Kustomize overlay directory
  file:
    path: "{{ _ansible_dir }}"
    state: directory

- name: Check to see if the project quota already exists
  stat:
    path: "{{ _ansible_dir }}/crq-{{ name.project }}.yml"
  register: project_quota

- name: Check to see if the limit range already exists
  stat:
    path: "{{ _ansible_dir }}/lr-{{ name.project }}.yml"
  register: project_limit_range

- name: Register the limit ranges 
  include_vars: 
    file: "{{ item }}"
    name: "limit_ranges"
  register: lrs
  with_fileglob:
    - lr-*.yml
    - lr-*.yaml

- name: Pull the relevant data and assign it to name_list
  set_fact:
    name_list: "{{ lrs.results | map(attribute='ansible_facts') | map(attribute='limit_ranges') | map(attribute='metadata') | map(attribute='namespace') }}"

#Temp - show the list for clarity
- name: Print name_list
  debug:
    var: name_list

- name: Create CRQ yml
  template: 
    src: templates/cluster_resource_quota.yml.j2
    dest: "{{ _ansible_dir }}/crq-{{ name.project }}.yml"

- name: Create LR yml
  template:
    src: templates/limit_range.yml.j2
    dest: "{{ _ansible_dir }}/lr-{{ name.project }}.yml"

- name: Generate Kustomize
  template: 
    src: templates/kustomization.yml.j2
    dest: "{{ _ansible_dir }}/kustomization.yml"
