---
- name: Create Kustomize overlay directory
  file:
    path: "{{ _ansible_dir }}"
    state: directory

- name: Check to see if the project quota already exists
  stat:
    path: "{{ _ansible_dir }}/crq-{{ name.namespace }}.yml"
  register: project_quota

- name: Check to see if the project quota already exists
  stat:
    path: "{{ _ansible_dir }}/lr-{{ name.project }}-{{ name.namespace }}.yml"
  register: project_limit_range

- name: Slurp
  slurp:
    src: "{{ _ansible_dir }}/lr-{{ name.project }}-{{ name.namespace }}.yml"
  register: slurp_lr
  when: project_limit_range.stat.exists

#FIXME
- name: Initial name_list
  set_fact:
    name_list: "{{ slurp_lr concatentated metadata.name into single list }}"

#TODO: Ensure `name_list` has a default value of [] prior to slurping
- name: Add namespace to list
  set_fact:
    name_list: "{{ name_list + item }}" 
  loop: 
    - "{{ name.namespace }}"
  when: project_limit_range.stat.exists

- name: Create CRQ yml
  template: 
    src: templates/clusetr_resource_quota.yml.j2
    dest: "{{ _ansible_dir }}/crq-{{ name.project }}.yml"

- name: Create LR yml
  template:
    src: templates/limit_range.yml.j2
    dest: "{{ _ansible_dir }}/lr-{{ name.project }}.yml"

- name: Generate Kustomize
  template: 
    src: templates/kustomization.yml.j2
    dest: "{{ _ansible_dir }}/kustomization.yml"
